"""empty message

Revision ID: 5324397c606a
Revises: ac33acaffc43
Create Date: 2019-03-08 08:10:14.299221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5324397c606a'
down_revision = 'ac33acaffc43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance', 'freq_miles',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('maintenance', 'freq_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('maintenance', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('maintenance', 'freq_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('maintenance', 'freq_miles',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
